name: Build Winutils for Hadoop 3.4.1

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Hadoop source
        uses: actions/checkout@v3
        with:
          repository: apache/hadoop
          ref: rel/release-3.4.1
          path: hadoop

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: 3.9.6

      - name: Build Hadoop native
        shell: cmd
        run: |
          cd hadoop
          mvn clean install -Pdist,native -DskipTests -Dtar

      - name: Build Hadoop native
        shell: cmd
        run: |
          dir hadoop/hadoop-dist/target/**/bin/

      - name: Upload winutils.exe
        uses: actions/upload-artifact@v4
        with:
          name: winutils
          path: hadoop/hadoop-dist/target/**/bin/**
