name: Build Hadoop Native Binaries for Windows

on:
  workflow_dispatch:
    inputs:
      hadoop_version:
        description: 'Comma-separated list of Hadoop versions (e.g., 3.3.6,3.4.1)'
        required: true
        default: '3.4.1'

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Install jq
        run: sudo apt-get install -y jq
      - name: Set matrix from input
        id: set-matrix
        run: |
          versions="${{ github.event.inputs.hadoop_version }}"
          versions_json=$(echo "$versions" | jq -R 'split(",") | map(gsub("^\\s+|\\s+$"; ""))')
          echo "matrix={\"version\": $versions_json}" >> "$GITHUB_OUTPUT"
        shell: bash
  
  build:
    needs: prepare
    runs-on: windows-latest
    strategy:
      matrix: ${{ fromJson(needs.prepare.outputs.matrix) }}

    steps:
      - name: Echo Hadoop version
        run: echo "Building For Hadoop ${{ matrix.version }}"
        
      - name: Set variables
        run: |
          echo "RELEASE_TAG=rel/release-${{ matrix.version }}" >> $env:GITHUB_ENV
          echo "DIST_VERSION=hadoop-${{ matrix.version }}" >> $env:GITHUB_ENV

      - name: Set up Dependencies (Java, CMake etc.)
        run: |
          choco install -y maven openjdk11 git winflexbison3 cmake protoc ninja
          echo "JAVA_HOME=C:\Program Files\OpenJDK\openjdk-11" >> $env:GITHUB_ENV
          echo "$env:ChocolateyInstall\\bin" >> $env:GITHUB_PATH
          echo "C:\Program Files\protoc\bin" >> $env:GITHUB_PATH
          echo "$env:JAVA_HOME\bin" | Out-File -FilePath $env:GITHUB_PATH -Append

      - name: Install Python 3
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2
        # with:
        #   vs-version: '[16.4,16.5)'

      - name: Cache Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-cache-${{ matrix.version }}
          restore-keys: |
            maven-cache-

      - name: Debug PATH and Java version
        shell: bash
        run: |
          echo "JAVA_HOME=$JAVA_HOME"
          java -version
          mvn -v
          where bash
          where protoc || echo "protoc not found"

      - name: Checkout Hadoop Source Code
        uses: actions/checkout@v3
        with:
          repository: apache/hadoop
          ref: ${{ env.RELEASE_TAG }}
          path: hadoop

      - name: Build Hadoop native binaries
        shell: cmd
        run: |
          cd hadoop
          mvn clean install -Pdist,native -DskipTests -Dtar -e -X
